name: ignition-dev

services:
  gateway-init:
    image: inductiveautomation/ignition:8.3.6

    environment:
      ACCEPT_IGNITION_EULA: "Y"
      IGNITION_UID: "${IGNITION_UID}"
      IGNITION_GID: "${IGNITION_GID}"

    command: >
      -n dev

    ports:
      - "8088:8088"

    volumes:
      - ignition-data:/usr/local/bin/ignition/data

volumes:
  ignition-data:
    name: ignition-dev-data
