services:
  gateway:
    image: inductiveautomation/ignition:8.3.6
    ports:
      - "8088:8088"

    command: >
      -n docker-test

    volumes:
      - gitops-data:/usr/local/bin/ignition/data
      - ./config/tag-definition:/usr/local/bin/ignition/data/config/resources/core/ignition/tag-definition/default
      - ./config/tag-type-definition:/usr/local/bin/ignition/data/config/resources/core/ignition/tag-type-definition/default

volumes:
  gitops-data:
