services:
  gateway:
    image: inductiveautomation/ignition:8.3.6
    user: "2003:2003"  # or chown the bind mounts to uid 2003
    volumes:
      - gitops-data:/usr/local/bin/ignition/data
      - ./config/tag-definition:/usr/local/bin/ignition/data/config/resources/core/ignition/tag-definition
      - ./config/tag-type-definition:/usr/local/bin/ignition/data/config/resources/core/ignition/tag-type-definition
    ports:
      - "8088:8088"
    command: >
      -n docker-test

volumes:
  gitops-data: